version: '3.3'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 3000:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  node-app:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest

volumes:
  mongo_data:
